# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['emoji_map', 'Subscript', 'Superscript', 'Highlight', 'Emoji', 'FootnoteEntry', 'FootnoteRef', 'Strikethrough',
           'AutoLink', 'AttrLink', 'FencedDiv', 'TagExtractor', 'opening_tag', 'LenientHtmlBlock',
           'ExtendedHtmlRenderer', 'parse_attrs']

# %% ../nbs/00_core.ipynb #4be85a97
from fastcore.utils import *
from threading import Lock
from mistletoe import Document, span_token
from mistletoe.html_renderer import HtmlRenderer
from mistletoe.span_token import SpanToken
from mistletoe.block_token import BlockToken, ListItem, List, reset_tokens, HTMLBlock

from html.parser import HTMLParser

# %% ../nbs/00_core.ipynb #58d557b5
_render_lock = Lock()

# %% ../nbs/00_core.ipynb #0d4a8105
class Subscript(SpanToken):
    pattern = re.compile(r"~([^~\s]+)~")
    parse_inner = False
    def __init__(self, match): self.content = match.group(1)

class Superscript(SpanToken):
    pattern = re.compile(r"\^([^\^\s]+)\^")
    parse_inner = False
    def __init__(self, match): self.content = match.group(1)

class Highlight(SpanToken):
    pattern = re.compile(r"==([^=]+)==")
    parse_inner = True
    def __init__(self, match): pass

# %% ../nbs/00_core.ipynb #d6a10481
emoji_map = {
    ':smile:':'😊', ':laughing:':'😆', ':joy:':'😂', ':grin:':'😁', ':wink:':'😉',
    ':heart:':'❤️', ':blue_heart:':'💙', ':green_heart:':'💚', ':yellow_heart:':'💛', ':purple_heart:':'💜',
    ':thumbsup:':'👍', ':thumbsdown:':'👎', ':clap:':'👏', ':wave:':'👋', ':raised_hands:':'🙌',
    ':rocket:':'🚀', ':fire:':'🔥', ':star:':'⭐', ':sparkles:':'✨', ':zap:':'⚡',
    ':check:':'✓', ':x:':'✗', ':warning:':'⚠️', ':no_entry:':'⛔', ':white_check_mark:':'✅',
    ':eyes:':'👀', ':thinking:':'🤔', ':tada:':'🎉', ':100:':'💯', ':muscle:':'💪',
    ':pray:':'🙏', ':ok_hand:':'👌', ':point_right:':'👉', ':point_left:':'👈',
    ':bug:':'🐛', ':construction:':'🚧', ':pencil:':'✏️', ':memo:':'📝', ':books:':'📚',
    ':bulb:':'💡', ':gear:':'⚙️', ':link:':'🔗', ':lock:':'🔒', ':key:':'🔑',
    ':package:':'📦', ':inbox_tray:':'📥', ':outbox_tray:':'📤', ':email:':'📧',
    ':camera:':'📷', ':computer:':'💻', ':iphone:':'📱', ':hourglass:':'⏳',
    ':sunny:':'☀️', ':cloud:':'☁️', ':umbrella:':'☂️', ':snowflake:':'❄️',
    ':pizza:':'🍕', ':coffee:':'☕', ':beer:':'🍺', ':cake:':'🍰',
    ':cat:':'🐱', ':dog:':'🐶', ':whale:':'🐳', ':snake:':'🐍'
}

class Emoji(SpanToken):
    pattern = re.compile(r':(\w+):')
    parse_inner = False
    def __init__(self, match): self.name = match.group(1)

# %% ../nbs/00_core.ipynb #8e730486
class FootnoteEntry(BlockToken):
    @staticmethod
    def start(line): return line.startswith('[^') and ']: ' in line
    
    @staticmethod
    def read(lines):
        line = next(lines)
        match = re.match(r'^\[\^(\w+)\]: (.+)$', line)
        return match
    
    def __init__(self, match):
        self.label = match.group(1)
        self.content = match.group(2)
        self.children = []

class FootnoteRef(SpanToken):
    pattern = re.compile(r'\[\^(\w+)\]')
    parse_inner = False
    def __init__(self, match): self.label = match.group(1)

# %% ../nbs/00_core.ipynb #37d30cba
class Strikethrough(SpanToken):
    pattern = re.compile(r'~~([^~]+)~~')
    parse_inner = True
    def __init__(self, match): pass

class AutoLink(SpanToken):
    pattern = re.compile(r'(?<!\()(https?://[^\s<>]+)')
    parse_inner = False
    precedence = 6
    def __init__(self, match): self.target = match.group(1)

# %% ../nbs/00_core.ipynb #dd4b0566
class AttrLink(SpanToken):
    pattern = re.compile(r'\[([^\]]+)\]\(([^)]+)\)\{([^}]+)\}')
    parse_inner,precedence = False,4
    def __init__(self, match): self.text, self.target, self.attr_str = match.group(1), match.group(2), match.group(3)

# %% ../nbs/00_core.ipynb #c2898abb
class FencedDiv(BlockToken):
    @staticmethod
    def start(line): return bool(re.match(r'^:{3,}\s*(\{|$)', line.strip()))

    @staticmethod
    def read(lines):
        line = next(lines)
        stripped = line.strip()
        n = len(stripped) - len(stripped.lstrip(':'))
        attr_str = stripped[n:].strip()
        inner = []
        for line in lines:
            if re.match(f'^:{{{n},}}\\s*$', line.strip()): break
            inner.append(line)
        return n, attr_str, inner

    def __init__(self, result):
        n, attr_str, inner = result
        self.attr_str = attr_str
        self.children = Document('\n'.join(inner)).children if inner else []

# %% ../nbs/00_core.ipynb #fb853efb
class TagExtractor(HTMLParser):
    def __init__(self):
        super().__init__()
        self.tag,self.attrs,self.self_closing = None,{},False
    def handle_starttag(self, tag, attrs):
        if self.tag is None: self.tag,self.attrs = tag,dict(attrs)
    def handle_startendtag(self, tag, attrs):
        if self.tag is None: self.tag,self.attrs,self.self_closing = tag,dict(attrs),True

def opening_tag(line):
    p = TagExtractor()
    try: p.feed(line)
    except: return None,{}
    if p.self_closing: return None,{}
    return p.tag,p.attrs


# %% ../nbs/00_core.ipynb #fdb920dd
def _fence_state(line, fence=None):
    m = re.match(r'^\s*(`{3,5}|~{3,5})', line)
    if not m: return fence
    s = m.group(1)
    if fence: return None if s[0] == fence[0] and len(s) >= len(fence) else fence
    return s

class LenientHtmlBlock(HTMLBlock):
    _extra_tags = {'svg'}
    _md_inner = False

    @classmethod
    def start(cls, line):
        if line[:1] in (' ', '\t'): return super().start(line)
        if not line.startswith('<'): return super().start(line)
        tag,attrs = opening_tag(line)
        if tag and tag in (span_token._tags | cls._extra_tags):
            cls._end_cond = f'</{tag}>'
            cls._md_inner = attrs.get('markdown') == '1'
            return 99
        return super().start(line)

    @classmethod
    def read(cls, lines):
        if cls._end_cond is None or not cls._end_cond.startswith('</'): return super().read(lines)
        buf,md,fence = [],cls._md_inner,None
        for line in lines:
            buf.append(line)
            if md: fence = _fence_state(line, fence)
            if (not md or fence is None) and cls._end_cond in line.casefold(): break
        if md: return ('md', buf[0], buf[1:-1], buf[-1] if len(buf)>1 else '')
        return buf

    def __init__(self, result):
        if isinstance(result, tuple) and result and result[0] == 'md':
            _,opener,inner,closer = result
            self.md_inner,self.opener,self.closer = True,opener,closer
            self.children = Document(inner).children if inner else []
        else:
            self.md_inner = False
            super().__init__(result)

# %% ../nbs/00_core.ipynb #be9bbac9
class ExtendedHtmlRenderer(HtmlRenderer):
    def __init__(self, *args, **kw): 
        super().__init__(LenientHtmlBlock, FencedDiv, AttrLink, Subscript, Superscript, Highlight, Emoji,
            FootnoteRef, FootnoteEntry, Strikethrough, AutoLink, *args, **kw)
        self.footnotes = {}
        ListItem.pattern = re.compile(r'( {0,3})(\d{1,9}[.)]|[+\-*])($|\s+)')
        List.pattern = re.compile(r' {0,3}(?:\d{1,9}[.)]|[+\-*])(?:[ \t]*$|[ \t]+)')
    def render_lenient_html_block(self, token):
        if not getattr(token, 'md_inner', False): return self.render_html_block(token)
        return f'{token.opener}{self.render_inner(token)}{token.closer}'
    def render_subscript(self, token): return f'<sub>{token.content}</sub>'
    def render_superscript(self, token): return f'<sup>{token.content}</sup>'
    def render_highlight(self, token): return f'<mark>{self.render_inner(token)}</mark>'
    def render_strikethrough(self, token): return f'<del>{self.render_inner(token)}</del>'
    def render_emoji(self, token): return emoji_map.get(f':{token.name}:', f':{token.name}:')
    def render_auto_link(self, token): return f'<a href="{token.target}">{token.target}</a>'
    def render_footnote_ref(self, token): 
        lbl = token.label
        return f'<sup><a href="#fn-{lbl}" id="fnref-{lbl}">[{lbl}]</a></sup>'
    def render_footnote_entry(self, token):
        lbl = token.label
        return f'<div id="fn-{lbl}" class="footnote"><sup>{lbl}</sup> {token.content} <a href="#fnref-{lbl}">↩</a></div>\n'
    def render_list_item(self, token):
        inner = self.render_inner(token)
        match = re.match(r'\[( |x|X)\] ', inner)
        if not match: return f'<li>{inner}</li>\n'
        checked = 'checked' if match.group(1).lower() == 'x' else ''
        checkbox = f'<input type="checkbox" disabled {checked}>'
        content = inner[match.end():]
        return f'<li>{checkbox} {content}</li>\n'
    def render_attr_link(self, token):
        attrs = parse_attrs('{' + token.attr_str + '}')
        return f'<a href="{token.target}"{attrs}>{token.text}</a>'
    def render_fenced_div(self, token):
        attrs = parse_attrs(token.attr_str) if token.attr_str else ''
        return f'<div{attrs}>\n{self.render_inner(token)}</div>\n'

    def __enter__(self):
        _render_lock.acquire()
        try: return super().__enter__()
        except:
            _render_lock.release()
            raise

    def __exit__(self, *exc):
        try: return super().__exit__(*exc)
        finally:
            reset_tokens()
            _render_lock.release()

# %% ../nbs/00_core.ipynb #5768db34
def parse_attrs(text):
    if not text: return ''
    pattern = r'#([^}\s]+)|\.([^}\s]+)|([\w-]+)="([^"]*)"'
    id_,classes,attrs = '',[],{}
    for match in re.finditer(pattern, text):
        id_m,cls,key,val = match.groups()
        if id_m: id_ = id_m
        elif cls: classes.append(cls)
        elif key: attrs[key] = val
    parts = []
    if id_: parts.append(f'id="{id_}"')
    if classes: parts.append(f'class="{" ".join(classes)}"')
    for k,v in attrs.items(): parts.append(f'{k}="{v}"')
    return ' ' + ' '.join(parts) if parts else ''

# %% ../nbs/00_core.ipynb #eeb3170d
@patch
def render_heading(self:ExtendedHtmlRenderer, token):
    inner = self.render_inner(token)
    attr_match = re.search(r'\s*\{([^}]+)\}$', inner)
    if attr_match:
        attrs = parse_attrs(attr_match.group(0))
        inner = inner[:attr_match.start()]
        return f'<h{token.level}{attrs}>{inner}</h{token.level}>'
    return f'<h{token.level}>{inner}</h{token.level}>'
